-- =====================================================================
-- Migração 40 — as Sugestões passam a ser da Garrafeira (03/10/2026)
--
-- O dono das apps: "quero mudar aqui a mecânica da coisa … aquilo da
-- pesquisa simples e pesquisa avançada é confuso!". As Sugestões eram a
-- página da WineSelection transposta (as Edge Functions `sugerir-vinho` e
-- `verificar-vinhos`, os dados no schema `wineselection`), e faziam tudo de
-- uma vez: ler a carta, perguntar ao catálogo e recomendar. Agora são
-- passos, e todos daqui (a WineSelection é para desligar):
--   1. LER a carta (a Edge Function `garrafeira-carta`, `acao:'ler'`) —
--      só a transcrição, guardada em `garrafeira.cartas`;
--   2. a app mostra só o que cabe no orçamento (+5 €) e, de cada vinho que
--      o Catálogo conhece, a nota do Vivino e a ficha (`carta_ligar`);
--   3. escolhem-se até 5 para o "Procurar informação" com IA de sempre
--      (`vinho-info`, que guarda no catálogo — `daCarta`);
--   4. a recomendação (`garrafeira-carta`, `acao:'recomendar'`), só com o
--      que o Catálogo sabe.
--
-- Três peças:
--  · `garrafeira.cartas` — uma linha por carta lida, de UMA pessoa (não é
--    conteúdo de uma garrafeira: é de quem foi jantar fora). Escreve-a só a
--    Edge Function (service role); quem a pediu lê-a pela policy.
--  · `garrafeira.carta_ligar(pedidos, ficha)` — a linha do catálogo de cada
--    vinho da carta, COM A COR: o branco nunca responde pelo tinto. Com
--    `ficha`, devolve também o que a linha sabe (só a Edge Function o pede).
--  · `garrafeira.marcas_amigos(pedidos)` — a da WineCatalog
--    (`winecatalog.marcas_amigos`, `db/amigos.sql` de lá) baralhava tintos
--    com brancos: as chaves (`chave_base`, `base_nome`) tiram a cor do nome
--    ("Papa Figos Branco" e "Papa Figos" dão a mesma), e a função nunca
--    olhava para ela. Esta compara a cor, e liga primeiro pela linha do
--    catálogo (`vinhos.catalogo_id`, migração 28) — é a ligação mais certa
--    que há. O resto é a regra de lá, tal e qual (quem é do grupo das Prendas
--    de Anos, o que sai e o que nunca sai).
--
-- Corre depois da 28 (`vinhos.catalogo_id`). Idempotente.
-- =====================================================================

-- ── 1. As cartas ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS garrafeira.cartas (
  id            bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quem          text         NOT NULL,
  prato         text         NOT NULL DEFAULT '',
  orcamento     numeric(8,2),
  fotos         integer      NOT NULL DEFAULT 0,
  -- a leitura: 'pendente' → 'lida' (ou 'erro')
  estado        text         NOT NULL DEFAULT 'pendente' CHECK (estado IN ('pendente', 'lida', 'erro')),
  vinhos        jsonb        NOT NULL DEFAULT '[]'::jsonb,   -- [{nome, produtor, ano, tipo, regiao, preco}]
  aviso         text,
  erro          text,
  -- os vinhos que se procuraram com IA: {"<índice>": "ok" | "falhou"}
  pesquisados   jsonb        NOT NULL DEFAULT '{}'::jsonb,
  -- a recomendação, que se pede depois e se pode pedir outra vez
  rec_estado    text         CHECK (rec_estado IN ('pendente', 'concluido', 'erro')),
  recomendacao  jsonb,
  rec_erro      text,
  criado_em     timestamptz  NOT NULL DEFAULT now(),
  atualizado_em timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS cartas_quem ON garrafeira.cartas (quem, criado_em DESC);

ALTER TABLE garrafeira.cartas ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON garrafeira.cartas FROM PUBLIC, anon, authenticated;
GRANT SELECT ON garrafeira.cartas TO authenticated;
GRANT ALL ON garrafeira.cartas TO service_role;
DROP POLICY IF EXISTS cartas_minhas ON garrafeira.cartas;
CREATE POLICY cartas_minhas ON garrafeira.cartas FOR SELECT TO authenticated
  USING (quem = lower(COALESCE(auth.email(), '')));

-- ── 2. A linha do catálogo de cada vinho da carta ────────────────────
-- Pedidos: [{nome, produtor, ano, tipo}] → [null | {id, ano, cor}] pela
-- mesma ordem (com `p_ficha`, também nome, produtor e a ficha da linha).
-- A colheita da carta primeiro; sem ela (ou sem essa colheita no
-- catálogo), a linha que a `achar` escolhe — a da mesma cor, a mais
-- completa. Uma linha fundida responde pela que ficou (a `achar` já o faz).
CREATE OR REPLACE FUNCTION garrafeira.carta_ligar(p_pedidos jsonb, p_ficha boolean DEFAULT false)
  RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER
  SET search_path = garrafeira, winecatalog, public
AS $$
BEGIN
  IF NOT (garrafeira.is_allowed() OR COALESCE(auth.role(), '') = 'service_role') THEN
    RAISE EXCEPTION 'Sem acesso.';
  END IF;
  IF jsonb_typeof(p_pedidos) IS DISTINCT FROM 'array' THEN RETURN '[]'::jsonb; END IF;
  RETURN (
    SELECT COALESCE(jsonb_agg(
             CASE WHEN w.id IS NULL THEN NULL
                  WHEN p_ficha THEN jsonb_build_object('id', w.id, 'ano', w.ano, 'cor', w.cor,
                                                       'nome', w.nome, 'produtor', w.produtor, 'ficha', w.ficha)
                  ELSE jsonb_build_object('id', w.id, 'ano', w.ano, 'cor', w.cor) END
             ORDER BY t.i), '[]'::jsonb)
      FROM jsonb_array_elements(p_pedidos) WITH ORDINALITY AS t(p, i)
      CROSS JOIN LATERAL (
        SELECT COALESCE(t.p ->> 'nome', '') AS n,
               COALESCE(t.p ->> 'produtor', '') AS pr,
               CASE WHEN jsonb_typeof(t.p -> 'ano') = 'number' THEN (t.p ->> 'ano')::integer END AS ano,
               NULLIF(t.p ->> 'tipo', '') AS tp
      ) c
      CROSS JOIN LATERAL (
        SELECT CASE WHEN winecatalog.chave_base(c.n, c.pr) = '' THEN NULL ELSE
                 COALESCE(CASE WHEN c.ano IS NOT NULL THEN winecatalog.achar(c.n, c.pr, c.ano, true, NULL, c.tp) END,
                          winecatalog.achar(c.n, c.pr, c.ano, false, NULL, c.tp)) END AS rid
      ) x
      LEFT JOIN winecatalog.vinhos w ON w.id = x.rid
     WHERE t.i <= 80
  );
END;
$$;
REVOKE ALL ON FUNCTION garrafeira.carta_ligar(jsonb, boolean) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION garrafeira.carta_ligar(jsonb, boolean) TO authenticated, service_role;

-- ── 3. As marcas dos amigos, com a cor ───────────────────────────────
-- Pedidos: [{nome, produtor, ano, tipo, catalogo_id}]. Um vinho de um
-- amigo é ESTE vinho se estiver ligado à mesma linha do catálogo, ou se a
-- chave bater E a cor não discordar (sem cor de um dos lados, a chave
-- chega — é o que a carta às vezes não diz). A cor do pedido é a que a
-- carta disse, senão a do nome, senão a da linha do catálogo.
-- SECURITY DEFINER pela mesma razão da de lá: lê as garrafeiras dos amigos,
-- que a RLS não deixa ver. Só responde a quem é do grupo e só conta as
-- garrafeiras cujo dono é do grupo; nunca sai a linha — nem notas, preço,
-- local ou fotografia: só o nome do amigo, quantas garrafas, as colheitas,
-- a nota e a data. Se mexeres em `garrafas.estado`, `consumo_avaliacao` ou
-- `desejado`, vê esta função E a `winecatalog.marcas_amigos` no mesmo dia.
CREATE OR REPLACE FUNCTION garrafeira.marcas_amigos(p_pedidos jsonb)
  RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER
  SET search_path = garrafeira, winecatalog, public
AS $$
DECLARE
  v_eu   text := lower(COALESCE(auth.email(), ''));
  v_nome text;
BEGIN
  IF v_eu = '' THEN RETURN NULL; END IF;
  SELECT a.nome INTO v_nome
    FROM anniversarygifts.amigos a
   WHERE a.ativo AND lower(a.email) = v_eu;
  IF v_nome IS NULL THEN RETURN NULL; END IF;
  IF jsonb_typeof(p_pedidos) IS DISTINCT FROM 'array' THEN RETURN '[]'::jsonb; END IF;
  RETURN (
    WITH am AS MATERIALIZED (
      SELECT a.nome, lower(a.email) AS email
        FROM anniversarygifts.amigos a
       WHERE a.ativo AND COALESCE(btrim(a.email), '') <> ''
    ),
    gv AS MATERIALIZED (
      SELECT am.nome AS amigo, v.desejado, v.ano,
             winecatalog.cor_de(v.tipo) AS cor,
             COALESCE(al.id_para, v.catalogo_id) AS cat,
             gs.stock, gs.aval_n, gs.media, gs.ultima,
             array_remove(ARRAY[NULLIF(winecatalog.chave_base(v.nome, v.produtor), ''),
                                winecatalog.base_nome(v.nome)], NULL) AS ks
        FROM garrafeira.vinhos v
        JOIN garrafeira.garrafeiras g ON g.id = v.garrafeira_id
        JOIN am ON am.email = lower(g.dono)
        LEFT JOIN winecatalog.alias al ON al.id_de = v.catalogo_id
        CROSS JOIN LATERAL (
          SELECT count(*) FILTER (WHERE ga.estado = 'na_garrafeira') AS stock,
                 count(*) FILTER (WHERE ga.estado = 'consumida' AND ga.consumo_avaliacao IS NOT NULL) AS aval_n,
                 avg(ga.consumo_avaliacao) FILTER (WHERE ga.estado = 'consumida') AS media,
                 max(ga.consumido_em) FILTER (WHERE ga.estado = 'consumida' AND ga.consumo_avaliacao IS NOT NULL) AS ultima
            FROM garrafeira.garrafas ga
           WHERE ga.vinho_id = v.id
        ) gs
    ),
    pr AS MATERIALIZED (
      SELECT e.aniversariante AS para, e.responsavel AS de, e.data, e.estado,
             winecatalog.cor_de(e.vinho ->> 'tipo') AS cor,
             array_remove(ARRAY[NULLIF(winecatalog.chave_base(e.vinho ->> 'nome', COALESCE(e.vinho ->> 'produtor', '')), ''),
                                winecatalog.base_nome(e.vinho ->> 'nome')], NULL) AS ks,
             (SELECT COALESCE(al.id_para, w.id)
                FROM winecatalog.vinhos w
                LEFT JOIN winecatalog.alias al ON al.id_de = w.id
               WHERE (e.vinho ->> 'catalogo_id') ~ '^[0-9]{1,18}$'
                 AND w.id = (e.vinho ->> 'catalogo_id')::bigint) AS cat
        FROM anniversarygifts.eventos e
       WHERE COALESCE(btrim(e.vinho ->> 'nome'), '') <> ''
         AND NOT (e.aniversariante = v_nome AND e.estado <> 'entregue')
    ),
    pq AS MATERIALIZED (
      SELECT t.i, c.n, c.pr, c.tp,
             COALESCE(
               (SELECT COALESCE(al.id_para, w.id)
                  FROM winecatalog.vinhos w
                  LEFT JOIN winecatalog.alias al ON al.id_de = w.id
                 WHERE w.id = c.cat),
               CASE WHEN winecatalog.chave_base(c.n, c.pr) <> ''
                    THEN winecatalog.achar(c.n, c.pr, c.ano, false, NULL, c.tp) END) AS rid
        FROM jsonb_array_elements(p_pedidos) WITH ORDINALITY AS t(p, i)
        CROSS JOIN LATERAL (
          SELECT COALESCE(t.p ->> 'nome', '') AS n,
                 COALESCE(t.p ->> 'produtor', '') AS pr,
                 CASE WHEN jsonb_typeof(t.p -> 'ano') = 'number' THEN (t.p ->> 'ano')::integer END AS ano,
                 NULLIF(t.p ->> 'tipo', '') AS tp,
                 CASE WHEN (t.p ->> 'catalogo_id') ~ '^[0-9]{1,18}$' THEN (t.p ->> 'catalogo_id')::bigint END AS cat
        ) c
       WHERE t.i <= 80
    ),
    ped AS MATERIALIZED (
      SELECT pq.i, pq.rid,
             COALESCE(winecatalog.cor_de(pq.tp), winecatalog.cor_do_nome(pq.n),
                      (SELECT w.cor FROM winecatalog.vinhos w WHERE w.id = pq.rid)) AS cor,
             ARRAY(
               SELECT DISTINCT k FROM (
                 SELECT NULLIF(winecatalog.chave_base(pq.n, pq.pr), '') AS k
                 UNION ALL SELECT winecatalog.base_nome(pq.n)
                 UNION ALL SELECT w.chave_base FROM winecatalog.vinhos w
                             LEFT JOIN winecatalog.alias al ON al.id_de = w.id
                            WHERE pq.rid IS NOT NULL AND COALESCE(al.id_para, w.id) = pq.rid
                 UNION ALL SELECT w.base_nome FROM winecatalog.vinhos w
                             LEFT JOIN winecatalog.alias al ON al.id_de = w.id
                            WHERE pq.rid IS NOT NULL AND COALESCE(al.id_para, w.id) = pq.rid
               ) z WHERE COALESCE(k, '') <> ''
             ) AS ks
        FROM pq
    ),
    -- um vinho de um amigo é ESTE: a mesma linha do catálogo, ou a chave
    -- com a cor a não discordar
    par AS MATERIALIZED (
      SELECT ped.i, gv.*
        FROM ped JOIN gv
          ON (gv.cat IS NOT NULL AND gv.cat = ped.rid)
          OR (gv.ks && ped.ks AND (ped.cor IS NULL OR gv.cor IS NULL OR gv.cor = ped.cor))
    ),
    marcas AS (
      SELECT ped.i,
        (SELECT jsonb_agg(jsonb_build_object('amigo', s.amigo, 'eu', s.amigo = v_nome,
                                             'garrafas', s.n, 'anos', s.anos)
                          ORDER BY s.amigo = v_nome DESC, s.amigo)
           FROM (SELECT par.amigo, sum(par.stock) AS n,
                        COALESCE(array_agg(DISTINCT par.ano ORDER BY par.ano) FILTER (WHERE par.ano IS NOT NULL), '{}') AS anos
                   FROM par WHERE par.i = ped.i AND par.stock > 0 AND NOT par.desejado
                  GROUP BY par.amigo) s) AS garrafeiras,
        (SELECT jsonb_agg(jsonb_build_object('amigo', s.amigo, 'eu', s.amigo = v_nome,
                                             'nota', s.nota, 'vezes', s.vezes, 'ultima', s.ultima)
                          ORDER BY s.amigo = v_nome DESC, s.nota DESC, s.amigo)
           FROM (SELECT par.amigo, sum(par.aval_n) AS vezes,
                        round(sum(par.media * par.aval_n) / sum(par.aval_n), 1) AS nota,
                        max(par.ultima) AS ultima
                   FROM par WHERE par.i = ped.i AND par.aval_n > 0
                  GROUP BY par.amigo) s) AS bebidos,
        (SELECT jsonb_agg(jsonb_build_object('amigo', s.amigo, 'eu', s.amigo = v_nome)
                          ORDER BY s.amigo = v_nome DESC, s.amigo)
           FROM (SELECT DISTINCT par.amigo FROM par
                  WHERE par.i = ped.i AND par.desejado) s) AS wishlist,
        (SELECT jsonb_agg(jsonb_build_object('para', pr.para, 'de', pr.de,
                                             'paraMim', pr.para = v_nome, 'deMim', pr.de = v_nome,
                                             'ano', extract(year FROM pr.data)::integer,
                                             'entregue', pr.estado = 'entregue')
                          ORDER BY pr.data DESC)
           FROM pr
          WHERE (pr.cat IS NOT NULL AND pr.cat = ped.rid)
             OR (pr.ks && ped.ks AND (ped.cor IS NULL OR pr.cor IS NULL OR pr.cor = ped.cor))) AS prendas
        FROM ped
    )
    SELECT COALESCE(jsonb_agg(
             CASE WHEN m.garrafeiras IS NULL AND m.bebidos IS NULL
                       AND m.wishlist IS NULL AND m.prendas IS NULL THEN NULL
                  ELSE jsonb_strip_nulls(jsonb_build_object(
                         'garrafeiras', m.garrafeiras, 'bebidos', m.bebidos,
                         'wishlist', m.wishlist, 'prendas', m.prendas))
             END ORDER BY m.i), '[]'::jsonb)
      FROM marcas m
  );
END;
$$;
REVOKE ALL ON FUNCTION garrafeira.marcas_amigos(jsonb) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION garrafeira.marcas_amigos(jsonb) TO authenticated;
