-- =====================================================================
-- Migração 49 — as colheitas que não batem certo (09/10/2026)
--
-- O dono das apps: "um menu no backoffice que me desse alertas como
-- duplicados e assim, que é quando tenho o mesmo vinho, diferentes
-- anos/colheitas e diferenças na caracterização". O preço até 20% é
-- aceitável; a nota global do Vivino diferente é erro; a da colheita só
-- com 0,3 ou mais; região, classificação, álcool, castas e harmonização
-- diferentes são sempre para analisar.
--
-- A DETEÇÃO não vive aqui: é a app que junta as colheitas do mesmo vinho
-- (`catFamChave`: nome, produtor e cor) e compara as fichas, sobre o
-- Catálogo que já tem em memória (`garrafeira.catalogo_vinhos`). Aqui fica
-- só o que tem de sobreviver ao aparelho: as diferenças que o admin olhou
-- e disse "está certo" — o álcool que muda de colheita para colheita, as
-- castas de um lote que mudou. Sem isto, a mesma lista voltava inteira a
-- cada visita, e um alerta que aparece sempre não se lê.
--
-- Uma diferença aceite é a de UM vinho (`chave`, a do `catFamChave`), de
-- UM campo, com uma ASSINATURA (calculada na app): os valores de cada
-- colheita nos campos estáveis, só as linhas no preço e na nota da
-- colheita (que mudam a cada corrida do script). Se os valores mudarem,
-- ou chegar outra colheita, a assinatura é outra e o alerta volta — foi
-- aceite o que se viu, não o que vier.
--
-- Desfazer não apaga: marca a linha (`desfeito_em`), como os links
-- retirados (migração 42). Só o admin do catálogo, pelas três funções;
-- a tabela não se lê nem escreve de fora (RLS ligada, sem policies).
--
-- Corre depois do `winecatalog` (usa a `winecatalog.sou_admin()`).
-- Idempotente.
-- =====================================================================

CREATE TABLE IF NOT EXISTS winecatalog.colheitas_aceites (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chave       text NOT NULL,
  campo       text NOT NULL,
  assinatura  text NOT NULL,
  valores     jsonb,
  quem        text,
  em          timestamptz NOT NULL DEFAULT now(),
  desfeito_em timestamptz,
  UNIQUE (chave, campo, assinatura)
);
ALTER TABLE winecatalog.colheitas_aceites ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON winecatalog.colheitas_aceites FROM public, anon, authenticated;

-- As que estão aceites (as desfeitas não).
CREATE OR REPLACE FUNCTION winecatalog.colheitas_aceites()
  RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
BEGIN
  IF NOT winecatalog.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin do catálogo.';
  END IF;
  RETURN (SELECT COALESCE(jsonb_agg(jsonb_build_object(
            'chave', a.chave, 'campo', a.campo, 'assinatura', a.assinatura,
            'valores', a.valores, 'quem', a.quem, 'em', a.em) ORDER BY a.em DESC), '[]'::jsonb)
            FROM winecatalog.colheitas_aceites a
           WHERE a.desfeito_em IS NULL);
END;
$$;

CREATE OR REPLACE FUNCTION winecatalog.colheitas_aceitar(
  p_chave text, p_campo text, p_assinatura text, p_valores jsonb DEFAULT NULL)
  RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
BEGIN
  IF NOT winecatalog.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin do catálogo.';
  END IF;
  IF COALESCE(btrim(p_chave), '') = '' OR COALESCE(p_campo, '') !~ '^[a-z][a-z0-9_]{0,39}$'
     OR COALESCE(btrim(p_assinatura), '') = '' THEN
    RAISE EXCEPTION 'Falta o vinho, o campo ou a assinatura.';
  END IF;
  INSERT INTO winecatalog.colheitas_aceites (chave, campo, assinatura, valores, quem)
  VALUES (left(p_chave, 400), p_campo, left(p_assinatura, 80), p_valores, lower(COALESCE(auth.email(), '')))
  ON CONFLICT (chave, campo, assinatura) DO UPDATE
     SET valores = EXCLUDED.valores, quem = EXCLUDED.quem, em = now(), desfeito_em = NULL;
  RETURN jsonb_build_object('ok', true);
END;
$$;

CREATE OR REPLACE FUNCTION winecatalog.colheitas_desaceitar(
  p_chave text, p_campo text, p_assinatura text)
  RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'winecatalog', 'public'
AS $$
BEGIN
  IF NOT winecatalog.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin do catálogo.';
  END IF;
  UPDATE winecatalog.colheitas_aceites
     SET desfeito_em = now()
   WHERE chave = p_chave AND campo = p_campo AND assinatura = p_assinatura
     AND desfeito_em IS NULL;
  RETURN jsonb_build_object('ok', true);
END;
$$;

REVOKE ALL ON FUNCTION winecatalog.colheitas_aceites() FROM public, anon;
REVOKE ALL ON FUNCTION winecatalog.colheitas_aceitar(text, text, text, jsonb) FROM public, anon;
REVOKE ALL ON FUNCTION winecatalog.colheitas_desaceitar(text, text, text) FROM public, anon;
GRANT EXECUTE ON FUNCTION winecatalog.colheitas_aceites() TO authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.colheitas_aceitar(text, text, text, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION winecatalog.colheitas_desaceitar(text, text, text) TO authenticated;
