-- =====================================================================
-- Garrafeira — Migração 09: importação de vinhos a partir de imagens
--
-- Correr uma vez numa base já existente. A seguir correr também
-- `db/functions.sql` e `db/policies.sql`, que criam o trigger e as RLS.
-- Esta tabela nunca guarda as fotografias: só o resultado temporário que a
-- pessoa irá rever antes de criar os vinhos e as garrafas.
-- =====================================================================

CREATE TABLE IF NOT EXISTS garrafeira.importacoes (
  id            bigint GENERATED BY DEFAULT AS IDENTITY,
  criado_em     timestamptz NOT NULL DEFAULT now(),
  quem          text NOT NULL DEFAULT '',
  garrafeira_id bigint NOT NULL REFERENCES garrafeira.garrafeiras (id) ON DELETE CASCADE,
  pedido        jsonb NOT NULL DEFAULT '{}'::jsonb,
  plano_ia      text NOT NULL DEFAULT 'sem_ia',
  estado        text NOT NULL DEFAULT 'pendente',
  resultado     jsonb,
  erro          text,
  CONSTRAINT importacoes_pkey PRIMARY KEY (id),
  CONSTRAINT importacoes_estado_chk CHECK (estado IN ('pendente','concluido','erro')),
  CONSTRAINT importacoes_plano_ia_chk CHECK (plano_ia IN ('sem_ia','gratis','premium'))
);

CREATE INDEX IF NOT EXISTS importacoes_quem_criado_idx ON garrafeira.importacoes (quem, criado_em DESC);
CREATE INDEX IF NOT EXISTS importacoes_garrafeira_idx ON garrafeira.importacoes (garrafeira_id, criado_em DESC);

GRANT ALL ON garrafeira.importacoes TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE garrafeira.importacoes_id_seq TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON garrafeira.importacoes TO service_role;
GRANT USAGE, SELECT ON SEQUENCE garrafeira.importacoes_id_seq TO service_role;

ALTER TABLE garrafeira.importacoes ENABLE ROW LEVEL SECURITY;
