-- =====================================================================
-- Migração 27 — notificações push (28/09/2026, o dono das apps: "as push
-- são importantes"). Corre DEPOIS da migração 26 (migracao-comentarios.sql)
-- e do db/comentarios.sql do WineCatalog, na versão com a conversa
-- (`comentarios_msgs`): os gatilhos penduram-se nessas duas tabelas.
--
-- O QUE AVISA, e a quem:
--   · um comentário ou sugestão NOVO            → o admin do catálogo
--   · quem escreveu RESPONDE (a uma dúvida…)    → o admin do catálogo
--   · o admin PERGUNTA, FECHA ou RECUSA         → quem escreveu
-- O admin recebe-os no telemóvel onde ligou as notificações da Garrafeira
-- (é a app que abre todos os dias; o WineCatalog abre pouco), e o toque
-- leva-o ao Alertas do WineCatalog.
--
-- O DESENHO É O DO GOALS, e pela lição de lá: as notificações do Goals
-- passaram semanas a parecer enviadas sem chegarem a lado nenhum. Por isso:
--   · os GATILHOS não mandam nada — escrevem numa CAIXA DE SAÍDA
--     (`push_avisos`), onde fica escrito, aviso a aviso, se chegou, a
--     quantos aparelhos, e porque não (sem ninguém com as notificações
--     ligadas, um endereço morto, o erro do serviço de push);
--   · e acordam a Edge Function `garrafeira-push` pelo `pg_net`, com a
--     `service_role_key` do cofre (Vault) — a mesma que o `goals-push-retry`
--     já usa. O pedido só sai depois do COMMIT (o `pg_net` é uma fila numa
--     tabela): uma escrita desfeita não avisa ninguém;
--   · o que ficar por enviar tenta-se outra vez de 30 em 30 minutos
--     (`garrafeira-push-retry`, pg_cron), até 10 vezes;
--   · nada disto pode deitar abaixo uma escrita: cada gatilho engole o seu
--     erro. A rede por baixo são os avisos DENTRO da app (a
--     `comentarios_avisos`, à entrada): um push que não chegue não perde
--     nada.
--
-- As subscrições são por PESSOA (email) e por aparelho (endpoint), não por
-- garrafeira — a exceção à regra do `garrafeira_id` do CLAUDE.md, porque
-- não é conteúdo de garrafeira nenhuma. Ninguém lhes toca por REST: entram
-- e saem pelas duas funções da app, e só a Edge Function as lê.
-- =====================================================================

CREATE TABLE IF NOT EXISTS garrafeira.push_subscriptions (
  endpoint  text NOT NULL,
  email     text NOT NULL,
  p256dh    text NOT NULL,
  auth_key  text NOT NULL,
  criado_em timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT push_subscriptions_pkey PRIMARY KEY (endpoint)
);
CREATE INDEX IF NOT EXISTS push_subscriptions_email_idx ON garrafeira.push_subscriptions (lower(email));
ALTER TABLE garrafeira.push_subscriptions ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS garrafeira.push_avisos (
  id           bigint GENERATED BY DEFAULT AS IDENTITY,
  email        text NOT NULL,                  -- a quem
  titulo       text NOT NULL,
  corpo        text NOT NULL,
  url          text,                           -- onde o toque leva
  origem       text,                           -- de que é ("comentario:12", "msg:40")
  criado_em    timestamptz NOT NULL DEFAULT now(),
  estado       text NOT NULL DEFAULT 'pendente', -- pendente | enviado | sem_subscricao | falhou
  tentativas   integer NOT NULL DEFAULT 0,
  em_envio_ate timestamptz,                    -- reservado por uma volta da função
  enviado_em   timestamptz,
  resultado    text,                           -- o que aconteceu, por palavras
  CONSTRAINT push_avisos_pkey PRIMARY KEY (id),
  CONSTRAINT push_avisos_estado_chk CHECK (estado IN ('pendente', 'enviado', 'sem_subscricao', 'falhou'))
);
CREATE INDEX IF NOT EXISTS push_avisos_pendentes_idx ON garrafeira.push_avisos (criado_em) WHERE estado = 'pendente';
CREATE INDEX IF NOT EXISTS push_avisos_email_idx ON garrafeira.push_avisos (lower(email), criado_em DESC);
ALTER TABLE garrafeira.push_avisos ENABLE ROW LEVEL SECURITY;


-- ---------------------------------------------------------------------
-- A APP: ligar e desligar as notificações neste aparelho, e saber se
-- estão ligadas. Um aparelho é de quem lá está agora: se o mesmo browser
-- já estava registado para outra pessoa, passa para esta.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION garrafeira.push_registar(p_endpoint text, p_p256dh text, p_auth text)
  RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'garrafeira', 'public'
AS $$
DECLARE v_email text := lower(COALESCE(auth.email(), ''));
BEGIN
  IF v_email = '' OR NOT garrafeira.is_allowed() THEN RAISE EXCEPTION 'Sem acesso à app.'; END IF;
  IF COALESCE(p_endpoint, '') !~ '^https://' OR length(p_endpoint) > 1000
     OR COALESCE(p_p256dh, '') = '' OR COALESCE(p_auth, '') = '' THEN
    RAISE EXCEPTION 'Subscrição inválida.';
  END IF;
  DELETE FROM garrafeira.push_subscriptions WHERE endpoint = p_endpoint;
  INSERT INTO garrafeira.push_subscriptions (endpoint, email, p256dh, auth_key)
  VALUES (p_endpoint, v_email, left(p_p256dh, 300), left(p_auth, 100));
  RETURN jsonb_build_object('ok', true);
END;
$$;

CREATE OR REPLACE FUNCTION garrafeira.push_retirar(p_endpoint text)
  RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'garrafeira', 'public'
AS $$
BEGIN
  DELETE FROM garrafeira.push_subscriptions
   WHERE endpoint = p_endpoint AND lower(email) = lower(COALESCE(auth.email(), ''));
  RETURN jsonb_build_object('ok', true);
END;
$$;

-- Este aparelho está registado para mim? E o último aviso que me mandaram,
-- com o que lhe aconteceu — é o que diz "chegou" ou "porque não chegou" sem
-- ninguém ter de ir ao SQL Editor.
CREATE OR REPLACE FUNCTION garrafeira.push_estado(p_endpoint text DEFAULT NULL)
  RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER
  SET search_path TO 'garrafeira', 'public'
AS $$
  SELECT jsonb_build_object(
    'registado', EXISTS (SELECT 1 FROM garrafeira.push_subscriptions
                          WHERE endpoint = p_endpoint AND lower(email) = lower(COALESCE(auth.email(), ''))),
    'aparelhos', (SELECT count(*) FROM garrafeira.push_subscriptions
                   WHERE lower(email) = lower(COALESCE(auth.email(), ''))),
    'ultimo', (SELECT jsonb_build_object('titulo', a.titulo, 'quando', a.criado_em,
                                         'estado', a.estado, 'resultado', a.resultado)
                 FROM garrafeira.push_avisos a
                WHERE lower(a.email) = lower(COALESCE(auth.email(), ''))
                ORDER BY a.criado_em DESC LIMIT 1));
$$;


-- ---------------------------------------------------------------------
-- A EDGE FUNCTION: reservar o que há para enviar (cada aviso numa volta
-- só — o gatilho e o cron podem acordá-la ao mesmo tempo) e escrever o que
-- aconteceu. Só a service_role.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION garrafeira.push_por_enviar(p_limite integer DEFAULT 50)
  RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'garrafeira', 'public'
AS $$
DECLARE v_res jsonb;
BEGIN
  WITH c AS (
    SELECT id FROM garrafeira.push_avisos
     WHERE estado = 'pendente' AND tentativas < 10
       AND (em_envio_ate IS NULL OR em_envio_ate < now())
     ORDER BY criado_em
     LIMIT LEAST(GREATEST(COALESCE(p_limite, 50), 1), 200)
     FOR UPDATE SKIP LOCKED
  ), u AS (
    UPDATE garrafeira.push_avisos a
       SET tentativas = a.tentativas + 1, em_envio_ate = now() + interval '2 minutes'
      FROM c WHERE a.id = c.id
    RETURNING a.*
  )
  SELECT COALESCE(jsonb_agg(jsonb_build_object(
           'id', u.id, 'titulo', u.titulo, 'corpo', u.corpo, 'url', u.url, 'origem', u.origem,
           'tentativas', u.tentativas,
           'subs', COALESCE((SELECT jsonb_agg(jsonb_build_object(
                               'endpoint', s.endpoint, 'p256dh', s.p256dh, 'auth_key', s.auth_key))
                               FROM garrafeira.push_subscriptions s
                              WHERE lower(s.email) = lower(u.email)), '[]'::jsonb)
         ) ORDER BY u.criado_em), '[]'::jsonb) INTO v_res
    FROM u;
  RETURN v_res;
END;
$$;

CREATE OR REPLACE FUNCTION garrafeira.push_resultado(
  p_id bigint, p_estado text, p_resultado text, p_mortos text[] DEFAULT NULL)
  RETURNS void LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'garrafeira', 'public'
AS $$
BEGIN
  UPDATE garrafeira.push_avisos
     SET estado       = CASE WHEN p_estado IN ('pendente', 'enviado', 'sem_subscricao', 'falhou')
                             THEN p_estado ELSE 'falhou' END,
         enviado_em   = CASE WHEN p_estado = 'enviado' THEN now() END,
         em_envio_ate = NULL,
         resultado    = left(p_resultado, 500)
   WHERE id = p_id;
  IF p_mortos IS NOT NULL AND cardinality(p_mortos) > 0 THEN
    DELETE FROM garrafeira.push_subscriptions WHERE endpoint = ANY (p_mortos);
  END IF;
END;
$$;


-- ---------------------------------------------------------------------
-- AVISAR: um aviso na caixa de saída, e a função acordada. Chamada pelos
-- gatilhos abaixo (e por qualquer coisa que venha a precisar de avisar
-- alguém nesta app). Se o `pg_net` ou o cofre falharem, o aviso fica lá e
-- o cron leva-o na volta seguinte.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION garrafeira.push_disparar()
  RETURNS void LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'garrafeira', 'public'
AS $$
BEGIN
  PERFORM net.http_post(
    url     := 'https://gjweqwfbnkgnibhajldc.supabase.co/functions/v1/garrafeira-push',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || (SELECT decrypted_secret FROM vault.decrypted_secrets
                                      WHERE name = 'service_role_key')),
    body    := jsonb_build_object('acao', 'enviar'));
EXCEPTION WHEN OTHERS THEN
  NULL;
END;
$$;

CREATE OR REPLACE FUNCTION garrafeira.push_avisar(
  p_email text, p_titulo text, p_corpo text, p_url text DEFAULT NULL, p_origem text DEFAULT NULL)
  RETURNS void LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'garrafeira', 'public'
AS $$
BEGIN
  IF COALESCE(btrim(p_email), '') = '' THEN RETURN; END IF;
  INSERT INTO garrafeira.push_avisos (email, titulo, corpo, url, origem)
  VALUES (lower(btrim(p_email)), left(p_titulo, 120), left(p_corpo, 400), p_url, p_origem);
  PERFORM garrafeira.push_disparar();
END;
$$;

-- O cron: só acorda a função se houver alguma coisa à espera.
CREATE OR REPLACE FUNCTION garrafeira.push_disparar_se_pendentes()
  RETURNS void LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'garrafeira', 'public'
AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM garrafeira.push_avisos
              WHERE estado = 'pendente' AND tentativas < 10) THEN
    PERFORM garrafeira.push_disparar();
  END IF;
  -- Os que gastaram as tentativas deixam de estar pendentes, e dizem-no.
  UPDATE garrafeira.push_avisos
     SET estado = 'falhou', resultado = COALESCE(resultado, '') || ' (desistiu ao fim de 10 tentativas)'
   WHERE estado = 'pendente' AND tentativas >= 10
     AND (em_envio_ate IS NULL OR em_envio_ate < now());
END;
$$;


-- ---------------------------------------------------------------------
-- OS GATILHOS dos comentários (as tabelas vivem no catálogo — ver
-- db/comentarios.sql do WineCatalog —, o canal é desta app). O texto do
-- aviso sai da base, nunca do browser.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION garrafeira.push_sobre(p_tipo text, p_nome text, p_ano integer)
  RETURNS text LANGUAGE sql IMMUTABLE
AS $$
  SELECT CASE WHEN p_tipo = 'vinho'
              THEN COALESCE(p_nome, 'um vinho') || COALESCE(' ' || p_ano::text, '')
              ELSE 'uma sugestão' END;
$$;

CREATE OR REPLACE FUNCTION garrafeira.comentarios_push_novo()
  RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'garrafeira', 'winecatalog', 'public'
AS $$
BEGIN
  BEGIN
    PERFORM garrafeira.push_avisar(
      winecatalog.admin_email(),
      CASE NEW.tipo WHEN 'vinho' THEN '💬 Comentário sobre um vinho' ELSE '💡 Nova sugestão' END,
      NEW.quem || ' · ' || garrafeira.push_sobre(NEW.tipo, NEW.nome, NEW.ano)
        || COALESCE(': ' || left(COALESCE(NEW.texto, NEW.link), 140), ''),
      '/WineCatalog/#alertas', 'comentario:' || NEW.id);
  EXCEPTION WHEN OTHERS THEN
    NULL;
  END;
  RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION garrafeira.comentarios_push_msg()
  RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'garrafeira', 'winecatalog', 'public'
AS $$
DECLARE
  c       winecatalog.comentarios%ROWTYPE;
  v_sobre text;
BEGIN
  BEGIN
    SELECT * INTO c FROM winecatalog.comentarios WHERE id = NEW.comentario_id;
    IF c.id IS NULL THEN RETURN NULL; END IF;
    v_sobre := garrafeira.push_sobre(c.tipo, c.nome, c.ano);
    IF NEW.de = 'admin' THEN
      -- Quem escreveu noutra app não tem as notificações ligadas aqui.
      IF c.app = 'garrafeira' THEN
        PERFORM garrafeira.push_avisar(
          c.quem,
          CASE NEW.estado WHEN 'duvida'    THEN '❓ O admin tem uma pergunta'
                          WHEN 'resolvido' THEN '✅ O teu comentário foi tratado'
                          ELSE '💬 O admin respondeu ao teu comentário' END,
          'Sobre ' || v_sobre || COALESCE(': ' || left(NEW.texto, 160), '.'),
          '/Garrafeira/#comentarios', 'msg:' || NEW.id);
      END IF;
    ELSE
      PERFORM garrafeira.push_avisar(
        winecatalog.admin_email(),
        '↩️ Resposta a um comentário',
        c.quem || ' · ' || v_sobre || COALESCE(': ' || left(NEW.texto, 160), ''),
        '/WineCatalog/#alertas', 'msg:' || NEW.id);
    END IF;
  EXCEPTION WHEN OTHERS THEN
    NULL;
  END;
  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS comentarios_push ON winecatalog.comentarios;
CREATE TRIGGER comentarios_push
  AFTER INSERT ON winecatalog.comentarios
  FOR EACH ROW EXECUTE FUNCTION garrafeira.comentarios_push_novo();

DROP TRIGGER IF EXISTS comentarios_msgs_push ON winecatalog.comentarios_msgs;
CREATE TRIGGER comentarios_msgs_push
  AFTER INSERT ON winecatalog.comentarios_msgs
  FOR EACH ROW EXECUTE FUNCTION garrafeira.comentarios_push_msg();


-- ---------------------------------------------------------------------
-- A NOVA TENTATIVA, de 30 em 30 minutos (a mesma cadência do Goals).
-- ---------------------------------------------------------------------
SELECT cron.unschedule(jobid) FROM cron.job WHERE jobname = 'garrafeira-push-retry';
SELECT cron.schedule('garrafeira-push-retry', '*/30 * * * *',
                     'SELECT garrafeira.push_disparar_se_pendentes()');


-- ---------------------------------------------------------------------
-- GRANTs. As tabelas: só a service_role (a Edge Function). A app só pelas
-- três funções de cima, que mexem nas linhas da própria pessoa.
-- ---------------------------------------------------------------------
REVOKE ALL ON garrafeira.push_subscriptions FROM PUBLIC, anon, authenticated;
REVOKE ALL ON garrafeira.push_avisos        FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON garrafeira.push_subscriptions TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON garrafeira.push_avisos        TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA garrafeira TO service_role;

REVOKE ALL ON FUNCTION garrafeira.push_registar(text, text, text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION garrafeira.push_retirar(text)              FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION garrafeira.push_estado(text)               FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION garrafeira.push_registar(text, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION garrafeira.push_retirar(text)              TO authenticated;
GRANT EXECUTE ON FUNCTION garrafeira.push_estado(text)               TO authenticated;

REVOKE ALL ON FUNCTION garrafeira.push_por_enviar(integer)                  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION garrafeira.push_resultado(bigint, text, text, text[]) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION garrafeira.push_por_enviar(integer)                  TO service_role;
GRANT EXECUTE ON FUNCTION garrafeira.push_resultado(bigint, text, text, text[]) TO service_role;

-- Estas não se chamam de fora: são dos gatilhos e do cron.
REVOKE ALL ON FUNCTION garrafeira.push_disparar()                               FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION garrafeira.push_disparar_se_pendentes()                  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION garrafeira.push_avisar(text, text, text, text, text)     FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION garrafeira.push_sobre(text, text, integer)               FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION garrafeira.comentarios_push_novo()                       FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION garrafeira.comentarios_push_msg()                        FROM PUBLIC, anon, authenticated;

-- Confirmar (as quatro de baixo sem ninguém; a app só as três de cima):
-- SELECT p.proname,
--        has_function_privilege('authenticated', p.oid, 'EXECUTE') AS auth,
--        has_function_privilege('anon',          p.oid, 'EXECUTE') AS anon
--   FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
--  WHERE n.nspname = 'garrafeira' AND p.proname LIKE '%push%';
