-- ---------------------------------------------------------------------
-- Migração 14 — vários comentários por consumo
--
-- Um vinho muda ao longo de uma refeição — "ainda fechado" no início,
-- "abriu bem depois de arejar" mais tarde — e uma nota só
-- (`garrafas.consumo_nota`) só guardava a última: editar era apagar a
-- anterior por cima. `consumo_notas` é uma linha por comentário, cada uma
-- com a sua hora. Data, local e avaliação continuam únicos por garrafa —
-- não mudam a meio da refeição, só o que se acha do vinho é que muda.
--
-- Correr DEPOIS desta: `db/functions.sql` (a nova `garrafeira_da_garrafa`
-- e o `consumir_garrafa`/`repor_garrafa` atualizados) e `db/policies.sql`
-- (as policies novas de `consumo_notas`).
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS garrafeira.consumo_notas (
  id         bigint GENERATED BY DEFAULT AS IDENTITY,
  garrafa_id bigint NOT NULL REFERENCES garrafeira.garrafas (id) ON DELETE CASCADE,
  nota       text NOT NULL,
  criado_em  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT consumo_notas_pkey PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS consumo_notas_garrafa_idx ON garrafeira.consumo_notas (garrafa_id);
ALTER TABLE garrafeira.consumo_notas ENABLE ROW LEVEL SECURITY;

-- A nota que já existia por garrafa passa a ser a primeira linha do
-- histórico dela — não se perde, só muda de casa.
INSERT INTO garrafeira.consumo_notas (garrafa_id, nota, criado_em)
SELECT id, consumo_nota, COALESCE(consumido_em::timestamptz, criado_em)
  FROM garrafeira.garrafas
 WHERE estado = 'consumida'
   AND consumo_nota IS NOT NULL
   AND btrim(consumo_nota) <> '';

ALTER TABLE garrafeira.garrafas DROP COLUMN IF EXISTS consumo_nota;
