-- Migração: cache de resultados da Edge Function `vinho-info`
CREATE TABLE IF NOT EXISTS garrafeira.catalogo_vinhos_cache (
  id            bigint GENERATED BY DEFAULT AS IDENTITY,
  criado_em     timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  chave         text NOT NULL,
  pedido        jsonb NOT NULL DEFAULT '{}'::jsonb,
  resultado     jsonb NOT NULL DEFAULT '{}'::jsonb,
  fontes        jsonb NOT NULL DEFAULT '[]'::jsonb,
  modelo        text NOT NULL DEFAULT '',
  modo          text NOT NULL DEFAULT 'barato',
  expira_em     timestamptz NOT NULL,
  CONSTRAINT catalogo_vinhos_cache_pkey PRIMARY KEY (id),
  CONSTRAINT catalogo_vinhos_cache_chave_uniq UNIQUE (chave),
  CONSTRAINT catalogo_vinhos_cache_modo_chk CHECK (modo IN ('barato','escalado'))
);

CREATE INDEX IF NOT EXISTS catalogo_vinhos_cache_expira_idx
  ON garrafeira.catalogo_vinhos_cache (expira_em);
CREATE INDEX IF NOT EXISTS catalogo_vinhos_cache_chave_idx
  ON garrafeira.catalogo_vinhos_cache (chave);

ALTER TABLE garrafeira.catalogo_vinhos_cache ENABLE ROW LEVEL SECURITY;
