-- =====================================================================
-- Garrafeira — Migração 07: uma garrafeira por pessoa
--
-- O QUE ISTO FAZ: a app deixa de ter UMA garrafeira (a de casa, vista por
-- toda a gente que lá entra) e passa a ter uma POR PESSOA. Mesma app,
-- mesmas tabelas, mesma base de dados — mas o João Mestre entra e vê a
-- garrafeira dele, vazia, e não vê uma única garrafa do Barrona enquanto o
-- Barrona não lha emprestar.
--
-- Correr no SQL Editor do Supabase, POR ESTA ORDEM:
--   1. este ficheiro
--   2. db/functions.sql   (as funções novas: e_dono, pode_ver, pode_mexer,
--                          garantir_garrafeira, transferir_garrafeira,
--                          e os triggers de guarda)
--   3. db/policies.sql    (as policies que passam a usá-las)
--
-- Entre o 1 e o 3 a app fica a ver tudo como antes (as policies velhas
-- ainda lá estão e só olham para `is_allowed()`); é só no fim do 3 que o
-- isolamento entra em vigor. Corre os três de seguida.
--
-- Idempotente: pode ser corrido outra vez sem estragar nada.
--
-- A GARRAFEIRA INICIAL: tudo o que está hoje na app é do Pedro Barrona, por
-- isso a garrafeira criada aqui chama-se "Garrafeira do Barrona". O DONO é
-- a conta que hoje é admin (`garrafeira.config.admin_email`) — que é a
-- conta onde estes dados de facto vivem. Quando o Barrona tiver a conta
-- dele, a passagem faz-se na app: Definições › A minha garrafeira › Passar
-- a garrafeira (`garrafeira.transferir_garrafeira`). Não é preciso SQL
-- nenhum para isso, e é de propósito.
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- 1. As tabelas novas
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS garrafeira.garrafeiras (
  id        bigint GENERATED BY DEFAULT AS IDENTITY,
  nome      text NOT NULL,
  dono      text NOT NULL,
  criado_em timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT garrafeiras_pkey PRIMARY KEY (id),
  CONSTRAINT garrafeiras_nome_chk CHECK (length(trim(nome)) > 0)
);
CREATE INDEX IF NOT EXISTS garrafeiras_dono_idx ON garrafeira.garrafeiras (lower(dono));

CREATE TABLE IF NOT EXISTS garrafeira.partilhas (
  garrafeira_id bigint NOT NULL REFERENCES garrafeira.garrafeiras (id) ON DELETE CASCADE,
  email         text NOT NULL,
  criado_em     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT partilhas_pkey PRIMARY KEY (garrafeira_id, email)
);
CREATE INDEX IF NOT EXISTS partilhas_email_idx ON garrafeira.partilhas (lower(email));

ALTER TABLE garrafeira.garrafeiras ENABLE ROW LEVEL SECURITY;
ALTER TABLE garrafeira.partilhas   ENABLE ROW LEVEL SECURITY;

-- As `ALTER DEFAULT PRIVILEGES` do schema.sql já cobrem tabelas criadas
-- depois delas, mas só para quem as criou — explícito é mais barato do que
-- descobrir um 403 na app.
GRANT ALL ON garrafeira.garrafeiras, garrafeira.partilhas TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON garrafeira.garrafeiras, garrafeira.partilhas TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA garrafeira TO anon, authenticated, service_role;

-- ---------------------------------------------------------------------
-- 2. As colunas novas — primeiro sem NOT NULL, que ainda não há o que lá pôr
-- ---------------------------------------------------------------------
ALTER TABLE garrafeira.locais   ADD COLUMN IF NOT EXISTS garrafeira_id bigint;
ALTER TABLE garrafeira.vinhos   ADD COLUMN IF NOT EXISTS garrafeira_id bigint;
ALTER TABLE garrafeira.garrafas ADD COLUMN IF NOT EXISTS garrafeira_id bigint;

-- ---------------------------------------------------------------------
-- 3. A garrafeira do Barrona, e tudo o que existe hoje lá dentro
-- ---------------------------------------------------------------------
DO $$
DECLARE
  v_gid  bigint;
  v_dono text := garrafeira.admin_email();
BEGIN
  SELECT id INTO v_gid FROM garrafeira.garrafeiras
   WHERE nome = 'Garrafeira do Barrona' ORDER BY id LIMIT 1;

  IF v_gid IS NULL THEN
    INSERT INTO garrafeira.garrafeiras (nome, dono)
    VALUES ('Garrafeira do Barrona', v_dono)
    RETURNING id INTO v_gid;
  END IF;

  -- Só as linhas ainda sem dono: correr isto outra vez depois de já haver
  -- garrafeiras de outras pessoas não lhes toca.
  UPDATE garrafeira.locais   SET garrafeira_id = v_gid WHERE garrafeira_id IS NULL;
  UPDATE garrafeira.vinhos   SET garrafeira_id = v_gid WHERE garrafeira_id IS NULL;
  UPDATE garrafeira.garrafas SET garrafeira_id = v_gid WHERE garrafeira_id IS NULL;

  -- Quem já tinha acesso à app via TUDO. Depois desta migração passaria a
  -- ver o seu próprio vazio, e uma app que esvazia sozinha parece avariada
  -- — por isso toda a gente que já lá estava fica com a garrafeira do
  -- Barrona emprestada. Para VER, que é o que passam a poder fazer.
  -- O dono não entra (uma partilha consigo próprio não quer dizer nada).
  INSERT INTO garrafeira.partilhas (garrafeira_id, email)
  SELECT v_gid, lower(email) FROM garrafeira.allowed_users
   WHERE lower(email) <> lower(v_dono)
  ON CONFLICT DO NOTHING;
END $$;

-- ---------------------------------------------------------------------
-- 4. Agora que estão todas preenchidas: NOT NULL, chaves e índices
-- ---------------------------------------------------------------------
ALTER TABLE garrafeira.locais   ALTER COLUMN garrafeira_id SET NOT NULL;
ALTER TABLE garrafeira.vinhos   ALTER COLUMN garrafeira_id SET NOT NULL;
ALTER TABLE garrafeira.garrafas ALTER COLUMN garrafeira_id SET NOT NULL;

ALTER TABLE garrafeira.locais   DROP CONSTRAINT IF EXISTS locais_garrafeira_fk;
ALTER TABLE garrafeira.locais   ADD  CONSTRAINT locais_garrafeira_fk
  FOREIGN KEY (garrafeira_id) REFERENCES garrafeira.garrafeiras (id) ON DELETE CASCADE;
ALTER TABLE garrafeira.vinhos   DROP CONSTRAINT IF EXISTS vinhos_garrafeira_fk;
ALTER TABLE garrafeira.vinhos   ADD  CONSTRAINT vinhos_garrafeira_fk
  FOREIGN KEY (garrafeira_id) REFERENCES garrafeira.garrafeiras (id) ON DELETE CASCADE;
ALTER TABLE garrafeira.garrafas DROP CONSTRAINT IF EXISTS garrafas_garrafeira_fk;
ALTER TABLE garrafeira.garrafas ADD  CONSTRAINT garrafas_garrafeira_fk
  FOREIGN KEY (garrafeira_id) REFERENCES garrafeira.garrafeiras (id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS locais_garrafeira_idx   ON garrafeira.locais (garrafeira_id);
CREATE INDEX IF NOT EXISTS vinhos_garrafeira_idx   ON garrafeira.vinhos (garrafeira_id);
CREATE INDEX IF NOT EXISTS garrafas_garrafeira_idx ON garrafeira.garrafas (garrafeira_id);

-- O nome do local era único no MUNDO. Duas pessoas têm as duas uma
-- "Garrafeira Principal" e uma "Cozinha" — a primeira a criá-la não pode
-- ficar com o nome preso para toda a gente.
ALTER TABLE garrafeira.locais DROP CONSTRAINT IF EXISTS locais_nome_uq;
ALTER TABLE garrafeira.locais ADD  CONSTRAINT locais_nome_uq UNIQUE (garrafeira_id, nome);

COMMIT;

-- ---------------------------------------------------------------------
-- Depois disto: correr db/functions.sql e db/policies.sql (por esta ordem).
-- Para confirmar, com a sessão de alguém que não seja o dono:
--   SELECT count(*) FROM garrafeira.vinhos;      -- 0 se não lhe emprestaram
--   SELECT * FROM garrafeira.garrafeiras;        -- só as dele e as recebidas
-- ---------------------------------------------------------------------
