-- ════════════════════════════════════════════════════════════════════════
-- Migração 46 — a IA olha para os produtores (05/10/2026)
-- ════════════════════════════════════════════════════════════════════════
-- O dono das apps: "dava jeito alguma coisa de IA aqui, seja IA automática,
-- seja IA manual, para analisar todos os produtores e tentar ver se existiam
-- duplicados, se existiam casas-mãe que fizessem sentido criar. Sempre com
-- ecrã de confirmação."
--
-- 1. `winecatalog.produtores_para_ia()`: a lista que vai à IA — cada produtor
--    confirmado (com as grafias e a casa-mãe) e cada grafia por confirmar, com
--    até quatro vinhos e as regiões. Só o admin do catálogo.
-- 2. `garrafeira.produtores_analises`: uma linha por análise automática (a
--    Edge Function `garrafeira-produtores` corre em segundo plano e a app
--    sonda-a, como as cartas das Sugestões). Só quem a pediu a lê.
-- Nada disto muda um produtor: as propostas aplicam-se na app, uma a uma e
-- confirmadas, pelas funções de sempre (`produtor_juntar`, `produtor_definir`,
-- `produtor_casa_mae`).

CREATE OR REPLACE FUNCTION winecatalog.produtores_para_ia()
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path TO 'winecatalog', 'public' AS $function$
BEGIN
  IF NOT winecatalog.produtores_autorizado() THEN
    RAISE EXCEPTION 'Só o admin do catálogo.';
  END IF;
  RETURN (
    WITH v AS MATERIALIZED (
      SELECT winecatalog.chave_produtor(x.produtor) AS k, x.nome, x.ficha ->> 'regiao' AS regiao
        FROM winecatalog.vinhos x
       WHERE COALESCE(x.produtor, '') <> ''
         AND NOT EXISTS (SELECT 1 FROM winecatalog.alias a WHERE a.id_de = x.id)
    ), g AS MATERIALIZED (
      SELECT x.produtor, x.chave, x.n_catalogo + x.n_garrafeiras AS n, pv.produtor_id
        FROM winecatalog.produtores_grafias() x
        LEFT JOIN winecatalog.produtor_variantes pv ON pv.chave = x.chave
       WHERE x.chave <> ''
    ), itens AS (
      SELECT jsonb_build_object(
               'nome', p.nome, 'confirmado', true, 'chave', winecatalog.chave_produtor(p.nome),
               'casa_mae', (SELECT m.nome FROM winecatalog.produtores m WHERE m.id = p.casa_mae_id),
               'grafias', (SELECT COALESCE(jsonb_agg(DISTINCT pv.escrito), '[]'::jsonb)
                             FROM winecatalog.produtor_variantes pv WHERE pv.produtor_id = p.id AND pv.escrito <> p.nome),
               'vinhos', (SELECT COALESCE(sum(g.n), 0) FROM g WHERE g.produtor_id = p.id),
               'exemplos', (SELECT COALESCE(jsonb_agg(DISTINCT e.nome), '[]'::jsonb) FROM (
                              SELECT v.nome FROM v JOIN winecatalog.produtor_variantes pv ON pv.chave = v.k
                               WHERE pv.produtor_id = p.id LIMIT 4) e),
               'regioes', (SELECT COALESCE(jsonb_agg(DISTINCT v.regiao), '[]'::jsonb) FROM v
                             JOIN winecatalog.produtor_variantes pv ON pv.chave = v.k
                            WHERE pv.produtor_id = p.id AND COALESCE(v.regiao, '') <> '')) AS j
        FROM winecatalog.produtores p
      UNION ALL
      SELECT jsonb_build_object(
               'nome', g.produtor, 'confirmado', false, 'chave', g.chave, 'casa_mae', null,
               'grafias', '[]'::jsonb, 'vinhos', g.n,
               'exemplos', (SELECT COALESCE(jsonb_agg(DISTINCT e.nome), '[]'::jsonb) FROM (
                              SELECT v.nome FROM v WHERE v.k = g.chave LIMIT 4) e),
               'regioes', (SELECT COALESCE(jsonb_agg(DISTINCT v.regiao), '[]'::jsonb) FROM v
                            WHERE v.k = g.chave AND COALESCE(v.regiao, '') <> ''))
        FROM g WHERE g.produtor_id IS NULL
    )
    SELECT jsonb_build_object(
      'produtores', (SELECT COALESCE(jsonb_agg(j ORDER BY lower(j ->> 'nome')), '[]'::jsonb) FROM itens),
      'distintos_chaves', (SELECT COALESCE(jsonb_agg(jsonb_build_array(d.chave_a, d.chave_b)), '[]'::jsonb)
                             FROM winecatalog.produtores_distintos d),
      'distintos_grafias', (SELECT COALESCE(jsonb_agg(jsonb_build_array(d.a, d.b)), '[]'::jsonb)
                              FROM winecatalog.produtores_distintos_grafias d))
  );
END;
$function$;
REVOKE ALL ON FUNCTION winecatalog.produtores_para_ia() FROM public, anon;
GRANT EXECUTE ON FUNCTION winecatalog.produtores_para_ia() TO authenticated;

CREATE TABLE IF NOT EXISTS garrafeira.produtores_analises (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quem text NOT NULL,
  estado text NOT NULL DEFAULT 'pendente' CHECK (estado IN ('pendente', 'concluida', 'erro')),
  resultado jsonb,
  erro text,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE garrafeira.produtores_analises ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON garrafeira.produtores_analises FROM public, anon, authenticated;
GRANT SELECT ON garrafeira.produtores_analises TO authenticated;
DROP POLICY IF EXISTS produtores_analises_minhas ON garrafeira.produtores_analises;
CREATE POLICY produtores_analises_minhas ON garrafeira.produtores_analises
  FOR SELECT TO authenticated USING (quem = lower(COALESCE(auth.email(), '')));
