-- =====================================================================
-- Garrafeira — Schema DDL (schema `garrafeira`)
-- Mesmo projeto Supabase do Goals/FestasBV/SplitBill
-- (diogoandrefsilva-personalapps-database), schema isolado — não mexe em
-- nada do que já lá está.
--
-- Correr no SQL Editor do Supabase, por esta ordem:
--   schema.sql -> functions.sql -> policies.sql
-- Ver db/README.md para os passos manuais (expor o schema na API, etc).
--
-- NOTA sobre IDs: cada mutação da app é um POST/PATCH/DELETE de UMA linha
-- (não há "gravar tudo em bloco"), por isso os `id` são
-- `GENERATED BY DEFAULT AS IDENTITY` e a app lê-os de volta da resposta do
-- POST (`Prefer: return=representation`) — nunca os inventa.
--
-- NOTA sobre o modelo: um VINHO (a referência: nome, ano, produtor, castas,
-- o que a IA descobriu) é uma coisa; uma GARRAFA (a coisa física, que está
-- num lugar e que se bebe um dia) é outra. Duas garrafas do mesmo vinho em
-- prateleiras diferentes são duas linhas em `garrafas` e UMA em `vinhos` —
-- é isso que evita ter a mesma ficha da IA copiada duas vezes, e é isso que
-- deixa "consumir" dar saída a uma garrafa sem apagar o que se sabe do vinho.
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS garrafeira;

-- A `service_role` (a Edge Function `vinho-info`) NÃO tem acesso a schemas
-- fora de `public` só por ser service_role — o bypass de RLS é sobre
-- policies, não sobre GRANTs. Sem isto, qualquer pedido feito com a
-- service_role key contra `garrafeira.*` falha com "permission denied for
-- schema garrafeira" (42501), silenciosamente do lado de quem chama. Foi
-- exatamente isso que fez as notificações push do Goals parecerem enviadas
-- sem nunca lá chegarem — GRANT explícito, sempre.
GRANT USAGE ON SCHEMA garrafeira TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA garrafeira TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA garrafeira TO service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA garrafeira GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA garrafeira GRANT USAGE, SELECT ON SEQUENCES TO service_role;

-- ---------------------------------------------------------------------
-- Controlo de acesso
-- ---------------------------------------------------------------------

-- `pode_editar` é o meio-termo que o Goals não tem: lá, quem não é admin é
-- só leitura. Aqui uma garrafeira é de casa — faz sentido que mais do que
-- uma pessoa possa dar saída a uma garrafa sem por isso poder mexer em
-- quem tem acesso à app. Admin = manda em tudo, inclusive nesta tabela;
-- editor = mexe em vinhos/garrafas/locais; o resto vê e procura.
CREATE TABLE IF NOT EXISTS garrafeira.allowed_users (
  email       text NOT NULL,
  nome        text NOT NULL DEFAULT '',
  pode_editar boolean NOT NULL DEFAULT false,
  created_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT allowed_users_pkey PRIMARY KEY (email)
);

CREATE TABLE IF NOT EXISTS garrafeira.access_requests (
  email        text NOT NULL,
  requested_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT access_requests_pkey PRIMARY KEY (email)
);

-- Configuração global (key-value).
--
-- `admin_email` está AQUI, e não fixo dentro de is_admin() como no Goals,
-- de propósito: esta app nasce com um dono para testes e passa depois para
-- outro (o Barrona). Com o email numa linha, essa passagem é um clique em
-- Definições (garrafeira.definir_admin) em vez de um deploy de SQL novo.
-- Quem lê isto é o `is_admin()` (SECURITY DEFINER) — a UI também lê, mas
-- só para saber que botões mostrar; quem decide é sempre a BD.
CREATE TABLE IF NOT EXISTS garrafeira.config (
  chave text NOT NULL,
  valor text NOT NULL,
  CONSTRAINT config_pkey PRIMARY KEY (chave)
);

INSERT INTO garrafeira.config (chave, valor)
VALUES ('admin_email', 'diogo.andre.f.silva@gmail.com'),
       ('moeda', 'EUR')
ON CONFLICT (chave) DO NOTHING;

-- ---------------------------------------------------------------------
-- Onde as garrafas moram
-- ---------------------------------------------------------------------

-- Uma linha por sítio da casa: "Garrafeira Principal", "Aparador da sala",
-- "Frigorífico da cozinha", "Móvel da garagem"…
--
-- As PRATELEIRAS não têm tabela própria de propósito: são texto livre na
-- garrafa (`garrafas.prateleira`). Uma tabela obrigava a criar a prateleira
-- antes de lá pôr a primeira garrafa, e a ordenação que uma tabela daria já
-- se consegue no cliente (`ordPrateleira` em app.js sabe que "Nível 2" vem
-- antes de "Nível 10"). Se um dia isto precisar de capacidade máxima por
-- prateleira, aí sim vale uma tabela.
CREATE TABLE IF NOT EXISTS garrafeira.locais (
  id        bigint GENERATED BY DEFAULT AS IDENTITY,
  nome      text NOT NULL,
  descricao text NOT NULL DEFAULT '',
  cor       text NOT NULL DEFAULT '#7b1f3d',
  ordem     integer NOT NULL DEFAULT 0,
  criado_em timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT locais_pkey PRIMARY KEY (id),
  CONSTRAINT locais_nome_uq UNIQUE (nome)
);

-- ---------------------------------------------------------------------
-- O vinho (a referência) e as suas castas
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS garrafeira.vinhos (
  id            bigint GENERATED BY DEFAULT AS IDENTITY,
  nome          text NOT NULL,
  produtor      text NOT NULL DEFAULT '',
  -- ano da colheita. NULL = sem colheita declarada (um lote, um espumante
  -- non-vintage) — não é "não sei", é "este vinho não tem ano".
  ano           integer,
  -- COR do vinho: 'Tinto' | 'Branco' | 'Rosé' | 'Espumante' | 'Licoroso' |
  -- 'Frisante'. É o eixo que toda a gente usa primeiro para procurar.
  tipo          text NOT NULL DEFAULT 'Tinto',
  -- ESTILO, que é coisa diferente da cor: 'Maduro' | 'Verde' |
  -- 'Colheita Tardia' | 'Palhete'. "Verde" não é uma cor — é a região/estilo
  -- (um Vinho Verde pode ser branco, tinto ou rosé), e por isso mistura-se
  -- mal com `tipo` se ficar no mesmo campo.
  estilo        text NOT NULL DEFAULT '',
  -- MENÇÃO de qualidade portuguesa: 'Reserva' | 'Grande Reserva' |
  -- 'Garrafeira' | 'Colheita Selecionada' | 'Vinhas Velhas' | 'Superior'…
  mencao        text NOT NULL DEFAULT '',
  -- CLASSIFICAÇÃO legal: 'DOC' | 'Vinho Regional' | 'Vinho'. Vem quase
  -- sempre da IA; raramente se escreve à mão.
  classificacao text NOT NULL DEFAULT '',
  regiao        text NOT NULL DEFAULT '',
  sub_regiao    text NOT NULL DEFAULT '',
  pais          text NOT NULL DEFAULT 'Portugal',
  teor          numeric(4,1),                  -- % de álcool
  estagio_meses integer,                       -- estágio em barrica/madeira
  estagio_texto text NOT NULL DEFAULT '',      -- "18 meses em barrica de carvalho francês"
  notas         text NOT NULL DEFAULT '',      -- notas próprias, escritas à mão
  -- Links à mão, escolhidos por quem usa a app: [{titulo,url}]. É diferente
  -- de `ai_fontes` (mais abaixo) — esse é o que a IA encontrou na última
  -- procura e é substituído por inteiro na procura seguinte; isto é do
  -- utilizador e a IA nunca lhe mexe.
  links         jsonb NOT NULL DEFAULT '[]'::jsonb,

  -- ── o que a IA/pesquisa descobriu (Edge Function `vinho-info`) ──
  -- Fica na mesma linha do vinho (e não numa tabela à parte) porque é UMA
  -- ficha por vinho, sempre substituída por inteiro na procura seguinte —
  -- não é histórico, é o estado atual do que se sabe.
  vivino_nota      numeric(3,2),               -- 0.00 a 5.00
  vivino_avaliacoes integer,
  vivino_url       text NOT NULL DEFAULT '',
  -- URL de uma foto do rótulo/garrafa (site do produtor, loja, Vivino…), não
  -- a imagem em si — guardar bytes numa coluna de texto é o que o Supabase
  -- Storage existe para evitar. Se o link morrer, procura-se de novo. Vazia
  -- na maioria dos vinhos (a IA nem sempre encontra uma, e ninguém é
  -- obrigado a pôr uma à mão) — sem ela, a app DESENHA a garrafa em SVG
  -- (cor do vidro pelo `tipo`, ano no rótulo) em vez de deixar um vazio.
  imagem_url       text NOT NULL DEFAULT '',
  -- A MINHA imagem, quando existe: o caminho dentro do bucket
  -- `garrafeira-rotulos` (ex.: 'v12/abc123.jpg'). Não é um URL — o bucket é
  -- privado e o link é assinado na hora (`assinarImagens()` em app.js).
  -- Quando está preenchida GANHA ao `imagem_url`: a fotografia de quem tem
  -- a garrafa na mão vale mais do que a que a IA encontrou numa loja. Apagar
  -- esta faz reaparecer a de baixo, que nunca se perde.
  imagem_path      text NOT NULL DEFAULT '',
  preco_medio      numeric(10,2),              -- EUR, garrafa de 0,75 L
  -- janela de consumo recomendada, em ANOS (não em idade): "beber entre
  -- 2026 e 2034". Guardado assim porque é o que as fichas dão e é o que
  -- deixa calcular "está no ponto?" sem saber a data de hoje ao gravar.
  beber_de         integer,
  beber_ate        integer,
  notas_prova      text NOT NULL DEFAULT '',
  harmonizacao     text NOT NULL DEFAULT '',
  ai_resumo        text NOT NULL DEFAULT '',
  ai_fontes        jsonb,                      -- [{titulo,url}] do grounding
  ai_modelo        text NOT NULL DEFAULT '',
  ai_atualizado_em timestamptz,

  criado_em     timestamptz NOT NULL DEFAULT now(),
  criado_por    text NOT NULL DEFAULT '',
  CONSTRAINT vinhos_pkey PRIMARY KEY (id),
  CONSTRAINT vinhos_ano_chk CHECK (ano IS NULL OR (ano BETWEEN 1900 AND 2100)),
  CONSTRAINT vinhos_vivino_chk CHECK (vivino_nota IS NULL OR (vivino_nota >= 0 AND vivino_nota <= 5)),
  CONSTRAINT vinhos_beber_chk CHECK (beber_ate IS NULL OR beber_de IS NULL OR beber_ate >= beber_de)
);
CREATE INDEX IF NOT EXISTS vinhos_nome_idx   ON garrafeira.vinhos (lower(nome));
CREATE INDEX IF NOT EXISTS vinhos_regiao_idx ON garrafeira.vinhos (regiao);
CREATE INDEX IF NOT EXISTS vinhos_ano_idx    ON garrafeira.vinhos (ano);

-- As castas são uma TABELA à parte (e não um campo de texto no vinho)
-- porque o requisito é procurar por casta: "mostra-me tudo o que tem
-- Touriga Nacional". Com texto livre, "Alicante Bouschet" e "Alicante
-- Bousquet" (as duas grafias aparecem nos dados de origem) seriam duas
-- coisas diferentes e a procura falhava metade das vezes.
-- Monocasta vs. várias castas NÃO é uma coluna: é a contagem das linhas
-- desta tabela para o vinho, calculada na app (`castaLabel`). Uma coluna
-- seria mais uma coisa para ficar dessincronizada ao editar as castas.
CREATE TABLE IF NOT EXISTS garrafeira.castas (
  id        bigint GENERATED BY DEFAULT AS IDENTITY,
  nome      text NOT NULL,
  cor       text NOT NULL DEFAULT '',   -- 'Tinta' | 'Branca' | '' (não se sabe)
  criado_em timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT castas_pkey PRIMARY KEY (id),
  CONSTRAINT castas_nome_uq UNIQUE (nome)
);

CREATE TABLE IF NOT EXISTS garrafeira.vinho_castas (
  vinho_id    bigint NOT NULL REFERENCES garrafeira.vinhos (id) ON DELETE CASCADE,
  casta_id    bigint NOT NULL REFERENCES garrafeira.castas (id) ON DELETE CASCADE,
  percentagem numeric(5,2),
  CONSTRAINT vinho_castas_pkey PRIMARY KEY (vinho_id, casta_id)
);
CREATE INDEX IF NOT EXISTS vinho_castas_casta_idx ON garrafeira.vinho_castas (casta_id);

-- ---------------------------------------------------------------------
-- A garrafa (a coisa física)
-- ---------------------------------------------------------------------

-- Uma linha por garrafa. Consumir NÃO apaga a linha: muda o `estado` para
-- 'consumida' e carimba a data, onde foi e o que se achou. É esse histórico
-- que responde a "onde é que bebi aquela relíquia?" — apagar a linha era
-- deitar isso fora, e é a única parte destes dados que não se recupera.
CREATE TABLE IF NOT EXISTS garrafeira.garrafas (
  id         bigint GENERATED BY DEFAULT AS IDENTITY,
  vinho_id   bigint NOT NULL REFERENCES garrafeira.vinhos (id) ON DELETE CASCADE,
  local_id   bigint REFERENCES garrafeira.locais (id) ON DELETE SET NULL,
  prateleira text NOT NULL DEFAULT '',   -- "Nível 3", "Prateleira de cima", ""
  lugar      text NOT NULL DEFAULT '',   -- "12", "A4" — a posição na prateleira
  formato    text NOT NULL DEFAULT '0,75 L',
  preco_compra numeric(10,2),
  comprado_em  date,
  entrada_em   date NOT NULL DEFAULT CURRENT_DATE,

  estado     text NOT NULL DEFAULT 'na_garrafeira',

  -- só preenchidos quando estado='consumida'
  consumido_em    date,
  consumo_local   text NOT NULL DEFAULT '',   -- "Jantar em casa do Barrona"
  consumo_nota    text NOT NULL DEFAULT '',   -- observações
  consumo_avaliacao integer,                  -- 1 a 5 estrelas, opcional

  criado_em  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT garrafas_pkey PRIMARY KEY (id),
  CONSTRAINT garrafas_estado_chk CHECK (estado IN ('na_garrafeira','consumida')),
  CONSTRAINT garrafas_aval_chk CHECK (consumo_avaliacao IS NULL OR consumo_avaliacao BETWEEN 1 AND 5),
  -- Uma garrafa consumida TEM de ter data. Sem isto, um PATCH a meio (rede
  -- a cair entre marcar o estado e gravar a data) deixava uma garrafa fora
  -- da garrafeira e fora do histórico — desaparecia das duas listas.
  CONSTRAINT garrafas_consumo_chk CHECK (estado <> 'consumida' OR consumido_em IS NOT NULL)
);
CREATE INDEX IF NOT EXISTS garrafas_vinho_idx  ON garrafeira.garrafas (vinho_id);
CREATE INDEX IF NOT EXISTS garrafas_local_idx  ON garrafeira.garrafas (local_id);
CREATE INDEX IF NOT EXISTS garrafas_estado_idx ON garrafeira.garrafas (estado);

-- ---------------------------------------------------------------------
-- Procuras à IA em segundo plano
-- ---------------------------------------------------------------------

-- Mesmo padrão do `goals.calendario_analises` (e da `sugerir-vinho` do
-- WineSelection): a procura com pesquisa Google demora MAIS do que um
-- pedido HTTP aguenta (o browser/iOS corta perto dos 60s). A Edge Function
-- cria aqui uma linha 'pendente', responde já com o `id`, e continua o
-- trabalho com `EdgeRuntime.waitUntil`; a app faz polling a esta linha.
-- Resolve também o telemóvel: bloquear o ecrã a meio já não mata a procura.
CREATE TABLE IF NOT EXISTS garrafeira.analises (
  id        bigint GENERATED BY DEFAULT AS IDENTITY,
  criado_em timestamptz NOT NULL DEFAULT now(),
  quem      text NOT NULL DEFAULT '',           -- email de quem carregou
  vinho_id  bigint REFERENCES garrafeira.vinhos (id) ON DELETE SET NULL,
  pedido    jsonb,                              -- {nome, ano, produtor, regiao}
  estado    text NOT NULL DEFAULT 'pendente',   -- 'pendente'|'concluido'|'erro'
  resultado jsonb,
  erro      text,
  CONSTRAINT analises_pkey PRIMARY KEY (id),
  CONSTRAINT analises_estado_chk CHECK (estado IN ('pendente','concluido','erro'))
);
CREATE INDEX IF NOT EXISTS analises_criado_idx ON garrafeira.analises (criado_em DESC);

-- Rasto de cada tentativa (browser -> Edge Function -> Gemini). Do lado do
-- browser vê-se sempre "HTTP 502"; a causa real está aqui.
CREATE TABLE IF NOT EXISTS garrafeira.sync_log (
  id        bigint GENERATED BY DEFAULT AS IDENTITY,
  criado_em timestamptz NOT NULL DEFAULT now(),
  origem    text NOT NULL DEFAULT 'function',   -- 'app' | 'function'
  acao      text NOT NULL DEFAULT 'vinho-info',
  estado    text NOT NULL DEFAULT 'ok',         -- 'pedido' | 'ok' | 'erro'
  quem      text,
  detalhe   jsonb,
  CONSTRAINT sync_log_pkey PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS sync_log_criado_idx ON garrafeira.sync_log (criado_em DESC);

-- ---------------------------------------------------------------------
-- GRANTs (sem isto: HTTP 403 / 42501 em tudo)
-- ---------------------------------------------------------------------
GRANT USAGE ON SCHEMA garrafeira TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA garrafeira TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA garrafeira TO anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA garrafeira GRANT ALL ON TABLES TO anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA garrafeira GRANT USAGE, SELECT ON SEQUENCES TO anon, authenticated;

-- ---------------------------------------------------------------------
-- RLS (as policies ficam em policies.sql, depois de functions.sql)
-- Nada aqui é legível pelo role `anon`: não há modo convidado nesta app.
-- ---------------------------------------------------------------------
ALTER TABLE garrafeira.allowed_users   ENABLE ROW LEVEL SECURITY;
ALTER TABLE garrafeira.access_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE garrafeira.config          ENABLE ROW LEVEL SECURITY;
ALTER TABLE garrafeira.locais          ENABLE ROW LEVEL SECURITY;
ALTER TABLE garrafeira.vinhos          ENABLE ROW LEVEL SECURITY;
ALTER TABLE garrafeira.castas          ENABLE ROW LEVEL SECURITY;
ALTER TABLE garrafeira.vinho_castas    ENABLE ROW LEVEL SECURITY;
ALTER TABLE garrafeira.garrafas        ENABLE ROW LEVEL SECURITY;
ALTER TABLE garrafeira.analises        ENABLE ROW LEVEL SECURITY;
ALTER TABLE garrafeira.sync_log        ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------
-- Storage: as fotografias dos rótulos tiradas por quem tem a garrafa
-- ---------------------------------------------------------------------
-- PRIVADO, como todo o resto desta app: os links são assinados na hora e
-- só quem tem acesso os consegue pedir. As fotos são tiradas em casa e
-- muitas vezes apanham a prateleira à volta — não é coisa para ficar num
-- URL público que qualquer um adivinha.
--
-- A app encolhe a imagem no browser antes de a enviar (lado maior 1000px,
-- JPEG) — uma foto de telemóvel são 4 MB, o rótulo chega com ~120 KB. O
-- limite abaixo é a rede de segurança, não o normal.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('garrafeira-rotulos', 'garrafeira-rotulos', false, 5242880,
        ARRAY['image/jpeg','image/png','image/webp'])
ON CONFLICT (id) DO NOTHING;
